# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for pyRSD.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create --name doc_env -f environment.yml

name: doc_env

channels:
- defaults
- conda-forge

dependencies:
- python=3.6
- numpy
- scipy
- pandas
- matplotlib
- IPython
- pip
- pip:
  - segpy
  - nbsphinx
  - sphinx_bootstrap_theme
  - sphinx-issues
